Fix build with gcc 9
This fixes the following errors:
Vector.h:

In file included from system/core/include/utils/SortedVector.h:26,
                 from system/core/include/utils/KeyedVector.h:26,
                 from system/core/include/utils/Looper.h:22,
                 from system/core/libutils/Looper.cpp:17:
system/core/include/utils/Vector.h: In member function ‘const android::Vector<T>& android::Vector<TYPE>::operator=(const android::Vector<TYPE>&) const’:
system/core/include/utils/Vector.h:251:64: error: cannot convert ‘const android::Vector<TYPE>*’ to ‘android::VectorImpl*’
  251 |     VectorImpl::operator = (static_cast<const VectorImpl&>(rhs));
      |                                                                ^

CallStack.cpp (I'm least proud about this):
In file included from /usr/include/c++/9/deque:67,
                 from system/core/include/backtrace/BacktraceMap.h:32,
                 from system/core/include/backtrace/Backtrace.h:27,
                 from system/core/libutils/CallStack.cpp:25:
/usr/include/c++/9/bits/stl_deque.h: In member function ‘void std::_Deque_base<_Tp, _Alloc>::_Deque_impl::_M_swap_data(std::_Deque_base<_Tp, _Alloc>::_Deque_impl&)’:
/usr/include/c++/9/bits/stl_deque.h:600:43: error: call of overloaded ‘swap(std::size_t&, std::size_t&)’ is ambiguous
  600 |    swap(this->_M_map_size, __x._M_map_size);
      |                                           ^

The Android.mk changes to turn off errors should be self-explanatory.

Change-Id: Id3eda073076a198aeed366e0947bed3a0e348b03